agency/agency/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    re_path('', include('apps.hitmen.urls')),
    re_path('', include('apps.hits.urls')),
]

agency/apps/hitmen/urls.py
from django.urls import path

from . import views

app_name = "hitmen_app"

urlpatterns = [
    path(
        '', 
        views.LoginUser.as_view(),
        name='hitman-login',
    ),
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='hitmen-register',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='hitman-logout',
    ),
    path(
        'hitmen/', 
        views.UserListView.as_view(),
        name='hitman-list',
    ),
    path(
        'hitmen/<int:pk>/', 
        views.UserDetailView.as_view(),
        name='hitman-detail',
    ),
]

agency/apps/hits/urls.py
from django.urls import path

from apps.hits import views

app_name = "hits_app"

urlpatterns = [
    path(
        'hits/create/', 
        views.HitRegisterView.as_view(),
        name='hit-register',
    ),
    path(
        'hits/bulk/', 
        views.HitAddBulkView.as_view(),
        name='hit-bulk',
    ),
    path(
        'hits/', 
        views.HitListView.as_view(),
        name='hit-list',
    ),
    path(
        'hits/<int:pk>/', 
        views.HitDetailView.as_view(),
        name='hit-detail',
    ),
]

agency/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/foundation-icons/foundation-icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <title>{% block title %}{% endblock title %}</title>
  {% block css %}{% endblock css %}
</head>
<body>

  {% block content %}
  {% endblock content %}

  {% block js %}
  
  {% endblock js %}
</body>
<script src="{% static 'js/vendor/jquery.js' %}"></script>
<script src="{% static 'js/vendor/what-input.js' %}"></script>
<script src="{% static 'js/vendor/foundation.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</html>

agency/templates/panel.html
{% extends "base.html" %}

{% load  static %}

{% block content %}

<div class="off-canvas-wrapper">
    <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
        <div class="off-canvas position-left reveal-for-large" id="my-info" data-off-canvas data-position="left" style="background-color: #424242;">
            <div class="row column">
              <h3 style="text-align: center; padding: 0.3em; color: #ffae00;">Spy Agency</h3>
              <ul class="vertical menu">
                  <li>
                    <a href="#"><span class="label warning">Hits</span></a>
                    <ul class="nested vertical menu">
                      <li>
                        <a href="{% url 'hits_app:hit-register' %}" style="color: white;">Create</a>
                      </li>
                      <li>
                        <a href="{% url 'hits_app:hit-list' %}" style="color: white;">List</a>
                      </li>
                    </ul>
                  </li>
              </ul>
              <ul class="vertical menu">
                <li>
                  <a href="#"><span class="label warning">Hitmen</span></a>
                  <ul class="nested vertical menu">
                    <li>
                      <a href="{% url 'hitmen_app:hitman-list' %}" style="color: white;">List</a>
                    </li>
                  </ul>
                </li>
            </ul>
            </div>
          </div>
        <div class="off-canvas-content" data-off-canvas-content>
            <div class="grid-x">
            <div class="cell top-bar" style="background-color: #424242;">
                <div class="top-bar-right">
                <a href="{% url 'hitmen_app:hitman-logout' %}">
                    <span class="label warning">Logout</span>
                </a>
                </div>
            </div>
            </div>
            <div class="grid-container" style="padding: 1em;">
            {% block panel-content %}
            {% endblock panel-content %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}