agency/agency/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    re_path('', include('apps.hitmen.urls')),
    re_path('', include('apps.hits.urls')),
]

agency/apps/hits/urls.py
from django.urls import path

from apps.hits import views

app_name = "hits_app"

urlpatterns = [
    path(
        'hits/create/', 
        views.HitRegisterView.as_view(),
        name='hit-register',
    ),
    path(
        'hits/bulk/', 
        views.HitAddBulkView.as_view(),
        name='hit-bulk',
    ),
    path(
        'hits/', 
        views.HitListView.as_view(),
        name='hit-list',
    ),
    path(
        'hits/<int:pk>/', 
        views.HitDetailView.as_view(),
        name='hit-detail',
    ),
]

agency/apps/hits/models.py
from django.db import models
from apps.hits.managers import HitManager
from django.conf import settings

class Hits(models.Model):
 # STATUS
    ASSIGNED = 1
    FAILLED_ASSIGNED = 2
    COMPLETED = 3
    

    STATUS_CHOICES = [
        (ASSIGNED, "Assigned"),
        (FAILLED_ASSIGNED, "Failled assigned"),
        (COMPLETED, "Completed")
    ]

    assigne = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="assigned_to",
        on_delete=models.CASCADE
    )
    description = models.CharField("Description", max_length=50, blank=True, null=True)
    target_name = models.CharField("Target Name", max_length=50)
    status = models.PositiveIntegerField(choices=STATUS_CHOICES, default=1)
    creator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="created_for",
        on_delete=models.CASCADE
    )

    objects = HitManager()

    class Meta:
        verbose_name = "Hit"
        verbose_name_plural = "Hits"
        

agency/apps/hits/forms.py
from apps.hits.models import Hits
from django import forms
from apps.hitmen.models import User


class HitAddForm(forms.ModelForm):
    class Meta:
        """Meta definition for HitAddForm."""

        model = Hits

        fields = (
            "assigne",
            "description",
            "target_name",
            "status",
            "creator",
        )
        widgets = {
            "assigne": forms.Select(
                attrs={
                    "placeholder": "Assigne ...",
                    "class": "input-group-field",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    "placeholder": "Description ...",
                    "class": "input-group-field",
                }
            ),
            "target_name": forms.TextInput(
                attrs={
                    "placeholder": "Targert Name ...",
                    "class": "input-group-field",
                }
            ),
            "status": forms.Select(
                attrs={
                    "placeholder": "Status ...",
                    "class": "input-group-field",
                }
            ),
            "creator": forms.Select(
                attrs={
                    "placeholder": "Creator ...",
                    "class": "input-group-field",
                }
            ),
        }

    def __init__(self, user, *args, **kwargs):
        super(HitAddForm, self).__init__(*args, **kwargs)
        self.fields["assigne"].queryset = User.objects.hitmen_to_select(user)
        self.fields["creator"].queryset = User.objects.filter(id=user.id)
        


class HitAddBulkForm(forms.ModelForm):
    class Meta:
        """Meta definition for HitAddForm."""

        model = Hits

        fields = (
            "assigne",
            "description",
            "target_name",
            "status",
            "creator",
        )
        widgets = {
            "assigne": forms.Select(
                attrs={
                    "placeholder": "Assigne ...",
                    "class": "input-group-field",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    "placeholder": "Description ...",
                    "class": "input-group-field",
                }
            ),
            "target_name": forms.TextInput(
                attrs={
                    "placeholder": "Targert Name ...",
                    "class": "input-group-field",
                }
            ),
            "status": forms.Select(
                attrs={
                    "placeholder": "Status ...",
                    "class": "input-group-field",
                }
            ),
            "creator": forms.Select(
                attrs={
                    "placeholder": "Creator ...",
                    "class": "input-group-field",
                }
            ),
        }

class HitUpdateForm(forms.ModelForm):
    class Meta:
        """Meta definition for HitUpdateForm."""

        model = Hits

        fields = (
            "assigne",
            "description",
            "target_name",
            "status",
            "creator",
        )
        widgets = {
            "assigne": forms.Select(
                attrs={
                
                    "placeholder": "Assigne ...",
                    "class": "input-group-field",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    
                    "placeholder": "Description ...",
                    "class": "input-group-field",
                }
            ),
            "target_name": forms.TextInput(
                attrs={
                    
                    "placeholder": "Targert Name ...",
                    "class": "input-group-field",
                }
            ),
            "status": forms.Select(
                attrs={
                    "placeholder": "Status ...",
                    "class": "input-group-field",
                }
            ),
            "creator": forms.Select(
                attrs={
                    
                    "placeholder": "Creator ...",
                    "class": "input-group-field",
                }
            ),
        }

agency/apps/hits/views.py
from apps.hitmen.mixins import (
    AdminAndManagersPermissionMixin,
    AutheticatedPermissionMixin,
)
from apps.hits.forms import HitAddForm, HitAddBulkForm, HitUpdateForm
from apps.hits.models import Hits
from django.views.generic import DetailView, ListView, UpdateView
from django.views.generic.edit import FormView
from apps.hitmen.managers import UserManager
from apps.hitmen.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy

class HitRegisterView(AdminAndManagersPermissionMixin, FormView):
    template_name = "hits/register.html"
    form_class = HitAddForm
    success_url = reverse_lazy("hits_app:hit-list")

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(user=self.request.user, **self.get_form_kwargs())

    def form_valid(self, form):

        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        
        return super(HitRegisterView, self).form_valid(form)




class HitAddBulkView(AdminAndManagersPermissionMixin, FormView):
    template_name = "hits/bulk.html"
    form_class = HitAddBulkForm
    success_url = "/hits"

    def form_valid(self, form):

        Hits.objects.create_hit(
            form.cleaned_data["assigne"],
            form.cleaned_data["description"],
            form.cleaned_data["target_name"],
            form.cleaned_data["status"],
            form.cleaned_data["creator"],
        )

        return super(HitAddBulkView, self).form_valid(form)


class HitDetailView(AutheticatedPermissionMixin, UpdateView):
    model = Hits
    template_name = "hits/detail.html"
    success_url = reverse_lazy("hits_app:hit-list")
    form_class = HitUpdateForm

    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object()

    #     return super().post(request, *args, **kwargs)
    
    # def form_valid(self, form):
    #     self.object = form.save(commit=False)
    #     self.object.save()

    #     return super(HitDetailView, self).form_valid(form)


class HitListView(AutheticatedPermissionMixin, ListView):
    template_name = "hits/list.html"
    context_object_name = "hits"
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Hits.objects.all()
        else:
            return Hits.objects.hits_of_hitmen(self.request.user.id)

agency/templates/hits/base_hits.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

agency/templates/hits/bulk.html
{% extends "hits/base_hits.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Register a Hit</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST">{% csrf_token %}
    
    <div class="cell medium-12">
      <label>Assigne:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.assigne }}
      </div>
      {% for error in form.assigne.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-12">
      <label>Description:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.description }}
      </div>
      {% for error in form.description.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Target Name:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-key"></i></span>
        {{ form.target_name }}
      </div>
      {% for error in form.target_name.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Creator:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-key"></i></span>
        {{ form.creator }}
      </div>
      {% for error in form.creator.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>

    <div class="cell medium-8">
      <button type="submit" class="cell success button" style="width: 200px;">Save</button>
      {% if object %}
      <a href="#" class="cell alert button clear">Remove</a>
      {% endif %}
    </div>
  </form>
</div>

{% endblock panel-content %}

agency/templates/hits/detail.html
{% extends "hits/base_hits.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Hit Detail</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST">{% csrf_token %}
    
    <div class="cell medium-12">
      <label>Assigne:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.assigne }}
      </div>
      {% for error in form.assigne.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-12">
      <label>Description:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.description }}
      </div>
      {% for error in form.description.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Target Name:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.target_name }}
      </div>
      {% for error in form.target_name.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Status:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.status }}
      </div>
      {% for error in form.status.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-12">
      <label>Creator:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.creator }}
      </div>
      {% for error in form.creator.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-8">
      <button type="submit" class="cell success button" style="width: 200px;">Save</button>
    </div>
  </form>
</div>
{% endblock panel-content %}

agency/templates/hits/list.html
{% extends "hits/base_hits.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
    <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Hits</h3>  
    <table class="cell">
        <thead>
            <th>Assigne</th>
            <th>Description</th>
            <th>Target Name</h>
            <th>Creator</h>
            <th>Status</h>
            <th>Detail</h>
        </thead>
        <tbody>
          {% for hit in hits %}
            <tr>
              <td>{{ hit.assigne }}</td>
              <td>{{ hit.description }}</td>
              <td>{{ hit.target_name }}</td>
              <td>{{ hit.creator }}</td>
              <td>
                {% if hit.status == 1 %}
                  <span class="label warning">Assigned</span>
                {% elif hit.status == 2 %}
                  <span class="label alert">Failled Assigned</span>
                {% else %}
                  <span class="label succes">Completed</span>
                {% endif %}
              </td>
              <td>
                <a href="{% url 'hits_app:hit-detail' hit.id %}" class="label warning"><i class="fi-eye"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
      </span>
  </div>
</div>

{% endblock panel-content %}

agency/templates/hits/register.html
{% extends "hits/base_hits.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Register a Hit</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST">{% csrf_token %}
    
    <div class="cell medium-12">
      <label>Assigne:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.assigne }}
      </div>
      {% for error in form.assigne.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-12">
      <label>Description:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.description }}
      </div>
      {% for error in form.description.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Target Name:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.target_name }}
      </div>
      {% for error in form.target_name.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Status:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.status }}
      </div>
      {% for error in form.status.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-12">
      <label>Creator:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.creator }}
      </div>
      {% for error in form.creator.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-8">
      <button type="submit" class="cell success button" style="width: 200px;">Save</button>
      {% if object %}
      <a href="#" class="cell alert button clear">Remove</a>
      {% endif %}
    </div>
  </form>
</div>

{% endblock panel-content %}