agency/agency/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    re_path('', include('apps.hitmen.urls')),
    re_path('', include('apps.hits.urls')),
]

agency/apps/hitmen/urls.py
from django.urls import path

from . import views

app_name = "hitmen_app"

urlpatterns = [
    path(
        '', 
        views.LoginUser.as_view(),
        name='hitman-login',
    ),
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='hitmen-register',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='hitman-logout',
    ),
    path(
        'hitmen/', 
        views.UserListView.as_view(),
        name='hitman-list',
    ),
    path(
        'hitmen/<int:pk>/', 
        views.UserDetailView.as_view(),
        name='hitman-detail',
    ),
]

agency/apps/hitmen/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

#
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    # STATUS
    ACTIVE = "A"
    INACTIVE = "I"
    #

    STATUS_CHOICES = [
        (ACTIVE, "Active"),
        (INACTIVE, "Inactive"),
    ]

    name = models.CharField("Name", max_length=30)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    description = models.TextField("Description", max_length=50, blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="A")
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="manager_of",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = ["name"]

    objects = UserManager()

agency/apps/hitmen/forms.py
from django import forms
from django.contrib.auth import authenticate

from .models import User


class UserRegisterForm(forms.ModelForm):

    password = forms.CharField(
        label="Password",
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "input-group-field",
            }
        ),
    )
    repeat_password = forms.CharField(
        label="Password",
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat Password",
                "class": "input-group-field",
            }
        ),
    )

    class Meta:
        """Meta definition for UserRegisterform."""

        model = User

        fields = (
            "name",
            "email",
        )
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "placeholder": "Name ...",
                    "class": "input-group-field",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "Email ...",
                    "class": "input-group-field",
                }
            ),
        }

    def clean_repeat_password(self):
        if self.cleaned_data["password"] != self.cleaned_data["repeat_password"]:
            self.add_error("repeat_password", "Passwords are not the same")


class LoginForm(forms.Form):
    email = forms.CharField(
        label="E-mail",
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input-group-field",
                "placeholder": "Email",
            }
        ),
    )
    password = forms.CharField(
        label="Password",
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "input-group-field", "placeholder": "password"}
        ),
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data["email"]
        password = self.cleaned_data["password"]

        if not authenticate(email=email, password=password):
            raise forms.ValidationError("The user data is not correct")
        return self.cleaned_data


class UserUpdateForm(forms.ModelForm):
    class Meta:

        model = User
        fields = (
            "email",
            "name",
            "description",
            "status",
            "manager",
        )
        widgets = {
            "email": forms.EmailInput(
                attrs={
                    
                    "placeholder": "Email ...",
                    "class": "input-group-field",
                }
            ),
            "name": forms.TextInput(
                attrs={
                    
                    "placeholder": "Name ...",
                    "class": "input-group-field",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    
                    "placeholder": "Description ...",
                    "class": "input-group-field",
                }
            ),
            "status": forms.Select(
                attrs={
                    "placeholder": "Status ...",
                    "class": "input-group-field",
                }
            ),
            "manager": forms.Select(
                attrs={
                    
                    "placeholder": "Manager ...",
                    "class": "input-group-field",
                }
            ),
        }


class UpdatePasswordForm(forms.Form):

    current_password = forms.CharField(
        label="Current Password",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "Current password"}),
    )
    new_password = forms.CharField(
        label="New Password",
        required=True,
        widget=forms.PasswordInput(attrs={"placeholder": "New password"}),
    )

agency/apps/hitmen/views.py
from apps.hitmen.forms import LoginForm, UserRegisterForm, UserUpdateForm
from apps.hitmen.mixins import (
    AdminAndManagersPermissionMixin,
    AutheticatedPermissionMixin,
)
from apps.hitmen.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View, UpdateView
from django.views.generic.edit import FormView


class UserRegisterView(FormView):
    template_name = "hitmen/register.html"
    form_class = UserRegisterForm
    success_url = "/"

    def form_valid(self, form):

        User.objects.create_user(
            form.cleaned_data["name"],
            form.cleaned_data["email"],
            form.cleaned_data["password"],
        )

        return super(UserRegisterView, self).form_valid(form)


class UserDetailView(AutheticatedPermissionMixin, UpdateView):
    model = User
    template_name = "hitmen/detail.html"
    form_class = UserUpdateForm
    success_url = reverse_lazy("hitmen_app:hitman-list")



class LoginUser(FormView):
    template_name = "hitmen/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("hits_app:hit-list")

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data["email"], password=form.cleaned_data["password"]
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect("/")


class UserListView(AdminAndManagersPermissionMixin, ListView):
    template_name = "hitmen/list.html"
    context_object_name = "hitmen"
    paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_superuser:
            return User.objects.all()
        else:
            return User.objects.hitmen_by_manager(self.request.user.id)

agency/templates/hitmen/base_users.html
{% extends "panel.html" %}

{% load  static %}

{% block css %}
{% endblock css %}

{% block js %}

{% endblock js %}

agency/templates/hitmen/detail.html
{% extends "hitmen/base_users.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
  <h5 class="cell" style="margin-bottom: 1em; text-align: center;">Hitman Detail</h5>  
  <div class="cell medium-9 grid-x grid-margin-x align-center">
    
    <div class="cell medium-7">
        <div class="card cell">
            <div class="card-section">
              <h4>{{ object.name }}</h4>
              <p><span style="font-weight: bold;">Email:</span> {{ object.email }}</p>
              <p><span style="font-weight: bold;">Description:</span> {{ object.description }}</p>
              <p><span style="font-weight: bold;">Status:</span> {{ object.status }}</p>
              <p><span style="font-weight: bold;">Manager:</span> {{ object.manager }}</p>
            </div>
        </div>
    </div>
{% endblock panel-content %}

agency/templates/hitmen/list.html
{% extends "hitmen/base_users.html" %}

{% load  static %}

{% block panel-content %}

<div class="grid-x grid-margin-x align-center">
    <h3 class="cell" style="margin-bottom: 1em; text-align: center;">System Hitmen</h3>  
    <table class="cell">
        <thead>
            <th>Email</th>
            <th>Name</th>
            <th>Status</h>
            <th>Detail</h>            
        </thead>
        <tbody>
          {% for hitman in hitmen %}
            <tr>
              <td>{{ hitman.email }}</td>
              <td>{{ hitman.name }}</td>
              <td>
                {% if hitman.status == "A" %}
                  <span class="label success">Active</span>
                {% else %}
                  <span class="label alert">Inactive</span>
                {% endif %}
              </td>
              <td>
                <a href="{% url 'hitmen_app:hitman-detail' hitman.id %}" class="label warning"><i class="fi-eye"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
      </span>
  </div>
</div>

{% endblock panel-content %}

agency/templates/hitmen/login.html
{% extends "base.html" %}

{% load  static %}

{% block content %}

<div class="grid-container">
  <div class="grid-y medium-grid-frame align-center">
    <div class="grid-x grid-padding-x align-center">
      <form class="cell medium-5 grid-x grid-margin-x"
        method="POST" 
        style="border: 1px solid #424242; padding: 2em; border-radius: 10px;"
      >{% csrf_token %}
        <h4 class="cell" style="text-align: center;">Acces to system</h4>
        <div class="cell medium-12">
          <label>Email:</label>
          <div class="input-group">
            <span class="input-group-label"><i class="fi-mail"></i></span>
            {{form.email}}
          </div>
        </div>
        <div class="cell medium-12">
          <label>Password:</label>
          <div class="input-group">
            <span class="input-group-label"><i class="fi-lock"></i></span>
            {{form.password}}
          </div>
        </div>
        <button type="submit" class="cell warning button">Enter</button>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

agency/templates/hitmen/register.html
{% extends "base.html" %}

{% load  static %}

{% block content %}

<div class="grid-x grid-margin-x align-center">
  <h3 class="cell" style="margin-bottom: 1em; text-align: center;">Welcome to Agency</h3>  
  <form class="cell medium-9 grid-x grid-margin-x" method="POST">{% csrf_token %}
    
    <div class="cell medium-12">
      <label>Name:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-book"></i></span>
        {{ form.name }}
      </div>
      {% for error in form.email.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-12">
      <label>Email:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-mail"></i></span>
        {{ form.email }}
      </div>
      {% for error in form.email.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Password:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-key"></i></span>
        {{ form.password }}
      </div>
      {% for error in form.password.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>
    <div class="cell medium-6">
      <label>Repeat Password:</label>
      <div class="input-group">
        <span class="input-group-label"><i class="fi-key"></i></span>
        {{ form.repeat_password }}
      </div>
      {% for error in form.repeat_password.errors %}
        <p class="cell" style="color: red;">
          {{ error|escape }}
        </p>
      {% endfor %}
    </div>

    <div class="cell medium-8">
      <button type="submit" class="cell success button" style="width: 200px;">Save</button>
      {% if object %}
      <a href="#" class="cell alert button clear">Remove</a>
      {% endif %}
    </div>
  </form>
</div>

{% endblock content %}